# Generated by Django 5.0.4 on 2024-04-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='updated_at',
        ),
    ]
