# Generated by Django 5.0.4 on 2024-04-25 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postalNo', models.IntegerField()),
                ('localAddress', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Stripe', 'Stripe'), ('CashOnDelivery', 'CashOnDelivery')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
    ]
